/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batches */
        get: operations["get_batches_api_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clearance-sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clearance Sites */
        get: operations["get_clearance_sites_api_clearance_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regain-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regain Records */
        get: operations["get_regain_records_api_regain_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Combined Records */
        get: operations["get_combined_records_api_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Batch */
        Batch: {
            /** Batch Id */
            batch_id: string;
            /** Batch Seq */
            batch_seq: number;
            /** Kiln Id */
            kiln_id: string;
            /** Operator Name */
            operator_name: string;
            /** Recorder Name */
            recorder_name: string;
            /** Feedstock Type */
            feedstock_type: string;
            /** Feedstock Appearance */
            feedstock_appearance: string;
            /** Feedstock Volume M3 */
            feedstock_volume_m3: number;
            /** Feedstock Weight Kg */
            feedstock_weight_kg?: number | null;
            /** Feedstock Drying Days */
            feedstock_drying_days: number;
            /** Feedstock Piece Size */
            feedstock_piece_size: string;
            /** Feedstock Source Desc */
            feedstock_source_desc: string;
            /** Feedstock Tracking Id */
            feedstock_tracking_id: string;
            /** Feedstock Lat */
            feedstock_lat: number;
            /** Feedstock Lon */
            feedstock_lon: number;
            /** Production Date */
            production_date: string;
            /** Production Lat */
            production_lat: number;
            /** Production Lon */
            production_lon: number;
            /** Quench Method */
            quench_method: string;
            /** Num Feed Cycles */
            num_feed_cycles: number;
            /** Weather Conditions */
            weather_conditions: string;
            /** Wind Shield Used */
            wind_shield_used: boolean;
            /** Temp Sensor Installed */
            temp_sensor_installed: boolean;
            /** Temp Peak C */
            temp_peak_c?: number | null;
            /** Temp Avg C */
            temp_avg_c?: number | null;
            /** Temp Duration Above 500 */
            temp_duration_above_500?: number | null;
            /** Biochar Visual Quality */
            biochar_visual_quality: string;
            /** Biochar Wet Weight Kg */
            biochar_wet_weight_kg: number;
            /** Biochar Volume L */
            biochar_volume_l?: number | null;
            /** Sample Collected */
            sample_collected: boolean;
            /** Sample Id */
            sample_id?: string | null;
            /** Uncharred Separated */
            uncharred_separated: boolean;
            /** Smoke Observation */
            smoke_observation: string;
            /** Safety Incidents */
            safety_incidents: string;
            /** Safety Details */
            safety_details: string;
            /** Operational Issues */
            operational_issues: string;
            /** Batch Notes */
            batch_notes: string;
            /** Pyrolysis Duration Min */
            pyrolysis_duration_min: number;
            /** Feeding Duration Min */
            feeding_duration_min: number;
            /** Yield Ratio Pct */
            yield_ratio_pct?: number | null;
            /** Form Version */
            form_version: string;
            /** Submission Time */
            submission_time: string;
            /** Media Expected */
            media_expected?: number | null;
            /** Media Received */
            media_received?: number | null;
            /** Photo Feedstock Pile */
            photo_feedstock_pile?: string | null;
            /** Photo Active Pyrolysis */
            photo_active_pyrolysis?: string | null;
            /** Photo Biochar Output */
            photo_biochar_output?: string | null;
            /** Photo Sample Bag */
            photo_sample_bag?: string | null;
            /** Dry Kg */
            dry_kg: number;
            /** Submission Lag Days */
            submission_lag_days: number;
            /** Photo Feedstock Pile Ok */
            photo_feedstock_pile_ok: boolean;
            /** Photo Active Pyrolysis Ok */
            photo_active_pyrolysis_ok: boolean;
            /** Photo Biochar Output Ok */
            photo_biochar_output_ok: boolean;
            /** Photo Sample Bag Ok */
            photo_sample_bag_ok: boolean;
            /** Photos Captured */
            photos_captured: number;
            /** Csi Photos Captured */
            csi_photos_captured: number;
            /** Quality Score */
            quality_score: number;
            /** C Feedstock Weight */
            c_feedstock_weight: boolean;
            /** C Feedstock Moisture */
            c_feedstock_moisture: boolean;
            /** C Feedstock Dryness */
            c_feedstock_dryness: boolean;
            /** C Biochar Weight */
            c_biochar_weight: boolean;
            /** C Visual Quality */
            c_visual_quality: boolean;
            /** C Quality Acceptable */
            c_quality_acceptable: boolean;
            /** C Sample Collected */
            c_sample_collected: boolean;
            /** C No Safety Incidents */
            c_no_safety_incidents: boolean;
            /** C Duration In Range */
            c_duration_in_range: boolean;
            /** C Operator Certified */
            c_operator_certified: boolean;
            /** C Photo Feedstock */
            c_photo_feedstock: boolean;
            /** C Photo Biochar */
            c_photo_biochar: boolean;
            /** C Photo Sample Bag */
            c_photo_sample_bag: boolean;
            /** C Temp Data */
            c_temp_data: boolean;
            /** Csi Compliant */
            csi_compliant: boolean;
            /** Compliance Fails */
            compliance_fails: number;
        };
        /** BiocharDataSourceResponse */
        BiocharDataSourceResponse: {
            /** Batches */
            batches: components["schemas"]["Batch"][];
            /**
             * Source
             * @enum {string}
             */
            source: "ona" | "db";
            /** Formid */
            formId?: string | null;
            /** Error */
            error?: string | null;
            /** Loadedat */
            loadedAt: string;
        };
        /** ClearanceDataSourceResponse */
        ClearanceDataSourceResponse: {
            /** Sites */
            sites: components["schemas"]["ClearanceSite"][];
            /** Formid */
            formId: string;
            /** Error */
            error?: string | null;
            /** Loadedat */
            loadedAt: string;
        };
        /** ClearanceSite */
        ClearanceSite: {
            /** Site Id */
            site_id: string;
            /** Polygon */
            polygon: Record<string, never>;
            /** Submission Id */
            submission_id: number;
            /** Submission Time */
            submission_time: string;
        };
        /**
         * CombinedRecordsResponse
         * @description biochar_batch + regain_kiln_operator merged into one view, tagged by
         *     data_source — mirrors field-manager-dashboard's
         *     load_combined_df_from_db() (pd.concat of the two DataFrames) and the
         *     "N full + M simplified = total" caption in its Batch Records tab.
         */
        CombinedRecordsResponse: {
            /** Records */
            records: Record<string, never>[];
            /** N Full */
            n_full: number;
            /** N Regain */
            n_regain: number;
            /** Total */
            total: number;
            /** Error */
            error?: string | null;
            /** Loadedat */
            loadedAt: string;
        };
        /** RegainDataSourceResponse */
        RegainDataSourceResponse: {
            /** Records */
            records: components["schemas"]["RegainRecord"][];
            /**
             * Source
             * @enum {string}
             */
            source: "ona" | "db";
            /** Formid */
            formId?: string | null;
            /** Error */
            error?: string | null;
            /** Loadedat */
            loadedAt: string;
        };
        /**
         * RegainRecord
         * @description regain_kiln_operator — simplified per-burn kiln log, kept separate from
         *     Batch because the form doesn't capture everything CSI compliance needs
         *     (visual quality, moisture, temperature). It does capture real feedstock
         *     weight, dry biochar output weight, and burn duration — those are NOT
         *     hardcoded to zero/false downstream; only fields genuinely absent from
         *     the form are.
         */
        RegainRecord: {
            /** Batch Id */
            batch_id: string;
            /** Today */
            today?: string | null;
            /** Production Date */
            production_date?: string | null;
            /** Operator Name */
            operator_name: string;
            /** Coop Name */
            coop_name?: string | null;
            /** Device Id */
            device_id: string;
            /** Kiln Number */
            kiln_number: string;
            /** Kiln Id */
            kiln_id: string;
            /** Production Lat */
            production_lat?: number | null;
            /** Production Lon */
            production_lon?: number | null;
            /** Num Bundles */
            num_bundles?: number | null;
            /** Feedstock Weight Kg */
            feedstock_weight_kg?: number | null;
            /** Quench Method */
            quench_method: string;
            /** Buckets Out */
            buckets_out?: number | null;
            /** Sample Collected */
            sample_collected: boolean;
            /** Photo Feedstock Pile */
            photo_feedstock_pile?: string | null;
            /** Photo Biochar Output */
            photo_biochar_output?: string | null;
            /** Pyrolysis Duration Min */
            pyrolysis_duration_min?: number | null;
            /** Biochar Dry Weight Kg */
            biochar_dry_weight_kg?: number | null;
            /** Submission Time */
            submission_time: string;
            /** Form Version */
            form_version: string;
            /** Instance Id */
            instance_id: string;
            /** Ona Id */
            ona_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_batches_api_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BiocharDataSourceResponse"];
                };
            };
        };
    };
    get_clearance_sites_api_clearance_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearanceDataSourceResponse"];
                };
            };
        };
    };
    get_regain_records_api_regain_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegainDataSourceResponse"];
                };
            };
        };
    };
    get_combined_records_api_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombinedRecordsResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
